import { useState } from "react";

export const useApp = () => {
  const [currentPage, setCurrentPage] = useState(1);

  const data: any = [];
  
  // const data: any = [
  //   {
  //     "Name of Distributor": "John okafor1",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Completed",
  //   },
  //   {
  //     "Name of Distributor": "James okafor2",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor3",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor4",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor5",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor6",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor7",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor8",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor9",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor10",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor11",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor12",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor13",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor14",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor15",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor16",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor17",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor18",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor19",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor20",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor21",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor22",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor23",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor24",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor25",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor26",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor27",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor28",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor29",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   },
  //   {
  //     "Name of Distributor": "James okafor30",
  //     Email: "shedinhoshedrach@gmail.com",
  //     "Name of Goods": "Iphone 100",
  //     "Total purchase": 5000,
  //     Amount: "N 300,000",
  //     "Date & Time": "2, 06, 2022, 10:00PM",
  //     Status: "Incomplete",
  //   }
  // ];
  const count = 5;

  return {
    data,
    currentPage,
    setCurrentPage,
    count,
  };
};
